### ISSUE TITLE
Image Concatination

### ISSUE THREAD

**Issue by john-tettis** [john-tettis/DAT_Extension#18]
Some projects require images for output. Some tasks could be made way clearer with multiple images. But only one image can be uploaded at a time.

Considering that I find it a huge hassle to use Canva or other services to concatinate images for this purpose, often adding 5 minutes to my time. Here is my solution:

Simply upload your images to the extension, the extension automatically concatinates them and spits it to downloads.

I got this one.

**Comment by ChuckTerry** [comment]
Dude, that's a great idea!  I usually end up tossing them in GIMP, but it will definitely save some time being able to do it from the extension.

**Comment by john-tettis** [comment]
Fixed in commit f8772948724dc0135e2144ecf5e31853b7d88a0e
