### ISSUE TITLE
Site update broke the qualifications' scrollview and the project sorting.

### ISSUE THREAD

**Issue by LilJaaY** [john-tettis/DAT_Extension#25]
Title basically. I like this project so I'll try to commit time this weekend to work on this issue if it's not dealt with by then.

![Screenshot from 2024-12-20 14-29-46](https://github.com/user-attachments/assets/bb9f5c0c-f236-47a1-80ac-b40c6a80563e)

**Comment by john-tettis** [comment]
I am on it! Thank you! Will fix and deploy today.

**Comment by john-tettis** [comment]
We were checking that the column headers were as we remembered -> Name, Pay, Tasks, Created,  Pin. But they added 'Hide" column which triggered our UI checker. Good to know that it is sensitive to that degree. Updated the logic to expect the hide column. Bingo!
